
DEVICE = "cuda"

#LLM
LLM_PROVIDER = "ollama"
LLM_MODEL = "bkai-foundation-models/vietnamese-bi-encoder"
TEMPERATURE = 0.0

#EMBEDDING
EMBEDDING_PROVIDER = "huggingface"
EMBEDDING_MODEL = "llama3"

#SPLITTER
CHUNK_SIZE = 200
CHUNK_OVERLAP = 50
STRATEGY = "sematic"
BREAKPOINT_THRESHOLD_TYPE = "percenile"
BREAKPOINT_THRESHOLD = 90.0

#VECTORSTORE
PERSIST_DIRECTORY = "./data/chroma_db"
PARENT_CHUNK_SIZE = 200
PARENT_CHUNK_OVERLAP = 50
CHILD_CHUNK_SIZE = 50
CHILD_CHUNK_OVERLAP = 10
TOP_K = 10

#CHAIN
RERANK_MODEL = "BAAI/bge-reranker-base"


